- name: Check if already installed
  shell: shairport-sync -V
  register: command_check
  failed_when: false

- name: Confirm to re-install or downgrade
  pause:
    prompt: "The following version of shairport-sync in installed:\n{{ command_check.stdout }}\nAre you sure you want to continue? (yes/no)"
  register: confirmation
  when: command_check.rc == 0

- name: continue or not?
  fail:
    msg: "User has stopped the installation"
  when: confirmation == "no"

- name: Check prerequisites
  include_tasks: prerequisites.yml

# update system
# sudo apt-get update
# sudo apt-get upgrade
- name: update
  include_tasks: update.yml

- name: Install git
  become: yes
  apt:
    name: git
    state: present

# disable wifi power saving
# sudo iwconfig wlan0 power off
- name: Turn off wifi power-saving
  shell: iwconfig wlan0 power off
  become: true

- name: Remove existing shairport-sync files
  block:
    # remove old scripts
    # location=$(which shairport-sync)
    # sudo rm $location
    - name: Find old shairport-sync command
      shell: which shairport-sync
      become: true
      register: command_locations
      failed_when: false

    - name: Remove old shairport-sync commands
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      with_items: command_locations

    # 5. Cleanup
    # sudo rm /etc/systemd/system/shairport-sync.service
    # sudo rm /etc/init.d/shairport-sync
    - name: Remove old shairport-sync service files
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      with_items:
        - "/etc/systemd/system/shairport-sync.service"
        - "/etc/init.d/shairport-sync"

# 6. REBOOT
- name: reboot
  become: yes
  reboot:

# Install Shairport-sync
# git clone https://github.com/mikebrady/shairport-sync.git
# git checkout development
- name: Git clone shairport-sync
  ansible.builtin.git:
    repo: 'https://github.com/mikebrady/shairport-sync.git'
    dest: /tmp/shairport-sync
    version: "{{ version }}"

- name: install shairport-sync - AirPlay 1
  include_tasks: airplay1.yml
  when: airplay_version == 1

- name: install shairport-sync - AirPlay 2
  include_tasks: airplay2.yml
  when: airplay_version == 2

- name: configure
  include_tasks: configure.yml

# systemctl enable shairport-sync
- name: systemctl enable shairport-sync
  ansible.builtin.systemd:
    name: shairport-sync
    enabled: yes
    daemon_reload: yes # https://github.com/ansible/ansible/issues/36585
  become: true

# systemctl start shairport-sync
- name: systemctl start shairport-sync
  ansible.builtin.systemd:
    name: shairport-sync
    state: started
    daemon_reload: yes # https://github.com/ansible/ansible/issues/36585
  become: true
